### ISSUE TITLE
Extender Default Gallery Image disappear when screen scrolls

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/a3-portfolio#10]
@alextuan Helo Tuan. We have 2 issues with Portfolio:

1. Extender Default Gallery Image disappear when screen scrolls
2. Extender bottom border cuts off Contact card added by Shortcode

Here is a video of that 2 issues:

https://screencast-o-matic.com/watch/cF12lVFiy3

**Comment by a3rev** [comment]
Fixed and released in [version 2.6.3](https://github.com/a3rev/a3-portfolio/releases/tag/2.6.3)
