### ISSUE TITLE
Icon conflict fontaweasome script 

### ISSUE THREAD

**Issue by a3rev** [a3rev/a3-portfolio#15]
@alextuan 

This is issue for 

font aweasome script that auto replace <i> tag that has class="fa" to <svg> file

Breaking icons on Expander and Gallery

**Comment by a3rev** [comment]
@alextuan 

As we discussed yesterday have to upgrade all plugins that use fontawesome with this fix.  Post a list here of plugins to be updated

- [x] WC Predictive Search Premium [v 4.6.10](https://www.dropbox.com/home/Steve/woocommerce%20predictive%20serach/PRO/Version%204.6.10)
- [x] WC Predictive Search Free [v 4.2.7](https://www.dropbox.com/home/Steve/woocommerce%20predictive%20serach/WordPress/Version%204.2.7)
- [x] WC Dynamic Gallery Premium [v 2.6.7](https://www.dropbox.com/home/Steve/woocommerce%20dynamic%20gallery/PRO/Version%202.6.7)
- [x] WC Dynamic Gallery Free [v 2.5.8](https://www.dropbox.com/home/Steve/woocommerce%20dynamic%20gallery/WordPress/Version%202.5.8)
- [x] WC Carousel & Slider  [v 1.9.8](https://www.dropbox.com/home/Steve/WooCommerce%20Carousel%20and%20Slider/Version%201.9.8)
- [x] WC Product Slider Free [v 1.6.9](https://www.dropbox.com/home/Steve/woocommerce%20widget%20product%20slider/WordPress/Version%201.6.9)
- [x] a3 Portfolio [v 2.7.5](https://www.dropbox.com/home/Steve/a3%20portfolio/Changelogs/Version%202.7.5)
- [x] a3 Portfolio Item Switcher [v 1.4.4](https://www.dropbox.com/home/Steve/a3%20portfolio/add-on%20plugins/a3%20portfolio%20item%20switcher/Changelogs/Version%201.4.4)
- [x] a3 Portfolio Dynamic Gallery [v 1.1.2](https://www.dropbox.com/home/Steve/a3%20portfolio/add-on%20plugins/a3%20portfolio%20dynamic%20gallery/Changelogs/Version%201.1.2)
- [x] a3 Responsive slider Premium [v 1.8.7](https://www.dropbox.com/home/Steve/a3%20responsive%20slider/Pro%20Version/Version%201.8.7)
- [x] a3 Responsive Slider Free [v 1.8.9](https://www.dropbox.com/home/Steve/a3%20responsive%20slider/WordPress/Version%201.8.9)
- [x] Page View Count [v 2.1.3](https://www.dropbox.com/home/Steve/Page%20Views%20Count/WordPress%20Versions/Version%202.1.3)

**Comment by alextuan** [comment]
I have done and edit correct list what plugins i have updated
So just need to have changelog to send them out

**Comment by alextuan** [comment]
@a3rev

**Comment by a3rev** [comment]
@alextuan Tuan - all changelogs are done and added - please send out and then close this issue

**Comment by alextuan** [comment]
I have send out all them and will close this issue now
