### ISSUE TITLE
Conflict with WordPress 6.0 FSE

### ISSUE THREAD

**Issue by sorina3rev** [a3rev/a3-portfolio#19]
@alextuan  @mrkunau Hello Tuan and Dat. While working on doc site on Portfolio I notice there is a conflict between wp site editor and our plug-in. Seems the wp full editor templates override the portfolio templates. I have test on a site that have Responsi with WordPress 5.9.3 and it is fine there. 

You can see the issue here: https://doc.a3de.info/portfolio-category/category-1/   https://doc.a3de.info/a3-portfolio/portfolio-item-1/
The only item that is pull from the portfolio post is the feature image, in rest nothing show on front end.

 -------------------------------
![screenshot](https://gyazo.com/e6b4e0497a5d684e9e646c3b2a6be154.png)
--------------------------------

![screenshot](https://gyazo.com/6d8ae10fdd1bfb10b6a896e1ae244f6d.png)

**Comment by a3rev** [comment]
Plugin updated for compatibility with WordPress 6.0 and FSE in [feature release version 3.0.0](https://github.com/a3rev/a3-portfolio/releases/tag/3.0.0)
