### ISSUE TITLE
Portfolio Taxonomy pages not showing item cards on other themes

### ISSUE THREAD

**Issue by a3rev** [a3rev/a3-portfolio#6]
It seems that a3 Portfolio Taxonomy pages - categories and tags are having issues - cannot show items on some themes - some sort of conflict

**Comment by alextuan** [comment]
Can you show me some website have this issue so that i can try upload latest code to see if it solve the issue

**Comment by a3rev** [comment]
Released in [version 2.6.1](https://github.com/a3rev/a3-portfolio/releases/tag/2.6.1)
