### ISSUE TITLE
Compliance with new GDPR laws

### ISSUE THREAD

**Issue by a3rev** [a3rev/a3-portfolio#9]
@alextuan Tuan - this is the issue for add GDPR compliance

**Comment by alextuan** [comment]
Below are privacy guide , please have read and edit it:

# What personal data we collect and why we collect it
**Suggested text (show to visitors):**
While you visit our site, we'll track what portfolios you've recently viewed.

## Cookies
**Suggested text (show to visitors):**
We use cookie to keep track of recently viewed and show it on widget. This cookie contains no personal data.

**Comment by a3rev** [comment]
Released in version 2.6.2 - [Commit 0b13300](https://github.com/a3rev/a3-portfolio/commit/0b13300bf6177646e6c052656ea182f2c865a0fa)
